using System.Text;

namespace BunnyGarden2FixMod.ConfigGen;

/// <summary>
/// Configs.yaml から docs/configs.md を生成する。各 section を見出し + テーブルでレンダリングし、
/// <see cref="SectionDef.Header"/> / <see cref="SectionDef.Footer"/> をテーブルの前後に挿入する。
/// </summary>
public static class MarkdownEmitter
{
    public static string Emit(List<SectionDef> sections)
    {
        var sb = new StringBuilder();
        sb.AppendLine("<!-- This file is auto-generated by ConfigGen from BunnyGarden2FixMod/Configs.yaml. Do not edit manually. -->");
        sb.AppendLine();
        sb.AppendLine("# Config 設定一覧");
        sb.AppendLine();
        sb.AppendLine("ゲームを一度起動すると `BepInEx/config/net.noeleve.BunnyGarden2FixMod.cfg` が生成されます。");
        sb.AppendLine("メモ帳などで開いて以下の項目を変更するか、ゲーム起動中に **F9** キーで設定パネルを開いて編集できます。");
        sb.AppendLine();

        foreach (var s in sections)
        {
            if (s.Hidden) continue;
            EmitSection(sb, s);
        }

        return sb.ToString();
    }

    private static void EmitSection(StringBuilder sb, SectionDef section)
    {
        var name = string.IsNullOrEmpty(section.Name) ? section.Section : section.Name;
        sb.Append("## [").Append(section.Section).Append("] ").AppendLine(name);
        sb.AppendLine();

        if (!string.IsNullOrEmpty(section.Header))
        {
            sb.AppendLine(section.Header.TrimEnd('\n'));
            sb.AppendLine();
        }

        sb.AppendLine("| キー | デフォルト | 説明 |");
        sb.AppendLine("|------|-----------|------|");
        foreach (var e in section.Configs)
        {
            EmitEntry(sb, e);
        }
        sb.AppendLine();

        if (!string.IsNullOrEmpty(section.Footer))
        {
            sb.AppendLine(section.Footer.TrimEnd('\n'));
            sb.AppendLine();
        }
    }

    private static void EmitEntry(StringBuilder sb, ConfigEntryDef e)
    {
        if (e.Type == "hotkey")
        {
            // hotkey は .cfg 上で {key}Key / {key}Button の 2 entry に展開されるため、表でも 2 行に分ける。
            // label には「のキーボードキー」「のボタン」を補い、Key 行と Button 行を見分けやすくする。
            var desc = (e.Description ?? string.Empty).TrimEnd('\n');
            var keyLabel = string.IsNullOrEmpty(e.Label) ? null : e.Label + "のキーボードキー";
            var btnLabel = string.IsNullOrEmpty(e.Label) ? null : e.Label + "のボタン";

            var keyCell = WithLabel(keyLabel, desc);
            sb.Append("| `").Append(e.EffectiveKey).Append("Key` | `").Append(e.DefaultKey).Append("` | ")
              .Append(Cell(keyCell)).AppendLine(" |");

            var btnDesc = desc;
            if (!string.IsNullOrEmpty(e.ControllerDescription))
            {
                var cd = e.ControllerDescription!.TrimEnd('\n');
                btnDesc = string.IsNullOrEmpty(btnDesc) ? cd : btnDesc + "\n" + cd;
            }
            var btnCell = WithLabel(btnLabel, btnDesc);
            var btnDefault = string.IsNullOrEmpty(e.DefaultButton) ? "None" : e.DefaultButton!;
            sb.Append("| `").Append(e.EffectiveKey).Append("Button` | `").Append(btnDefault).Append("` | ")
              .Append(Cell(btnCell)).AppendLine(" |");
        }
        else
        {
            var def = e.Default?.ToString() ?? string.Empty;
            var desc = WithLabel(e.Label, (e.Description ?? string.Empty).TrimEnd('\n'));
            sb.Append("| `").Append(e.EffectiveKey).Append("` | `").Append(def).Append("` | ")
              .Append(Cell(desc)).AppendLine(" |");
        }
    }

    /// <summary>
    /// 説明列に label を見出しとして前置する。両方ある場合は「{label}\n{description}」（Cell で &lt;br&gt; 化）、
    /// 片方のみなら片方を返す。
    /// </summary>
    private static string WithLabel(string? label, string description)
    {
        if (string.IsNullOrEmpty(label)) return description;
        if (string.IsNullOrEmpty(description)) return label!;
        return label + "\n" + description;
    }

    /// <summary>
    /// Markdown テーブルセル用にエスケープと改行変換を行う。
    /// `\` を先に二重化してから `|` を `\|` にすることで、入力に既に `\` が含まれていた場合でも
    /// 順序由来の崩れが起きないようにする（CodeEmitter.ToCSharpStringLiteral と同じ並び）。
    /// </summary>
    private static string Cell(string text)
    {
        if (string.IsNullOrEmpty(text)) return "";
        return text
            .Replace("\\", "\\\\")
            .Replace("|", "\\|")
            .Replace("\r\n", "\n")
            .Replace("\n", "<br>");
    }
}
