// <auto-generated>
//   This file is generated by ConfigGen. Do not edit manually.
//   Source: Configs.yaml
// </auto-generated>
#nullable disable
using BepInEx.Configuration;
using System;

namespace BunnyGarden2FixMod;

public static class Configs
{
    // ─── 静的フィールド ──────────────────────────────
    public static ConfigEntry<int> Width;
    public static ConfigEntry<int> ExtraWidth;
    public static ConfigEntry<int> FrameRate;
    public static ConfigEntry<UnityEngine.InputSystem.Key> TimeStopToggleKey;
    public static global::BunnyGarden2FixMod.Utils.HotkeyConfig SampleHotkey;
    public static ConfigEntry<bool> SampleToggle;
    public static ConfigEntry<float> SampleSlider;

    // ─── BindAll: Plugin.Awake から1回呼ぶ ──────────
    public static void BindAll(ConfigFile cfg)
    {
        Width = cfg.Bind("Resolution", "Width",
            1920,
            @"解像度の幅（横）を指定します");

        ExtraWidth = cfg.Bind("Resolution", "ExtraWidth",
            2560,
            @"ゲーム内 OptionMenu の DISPLAY 項目に追加される拡張解像度（ウィンドウモード）の幅。
既定 2560（WQHD）。16:9 を推奨。");

        FrameRate = cfg.Bind("Display", "FrameRate",
            60,
            new ConfigDescription(
                @"フレームレート上限",
                new AcceptableValueRange<int>(30, 240)));

        TimeStopToggleKey = cfg.Bind("Hotkey", "TimeStopToggleKey",
            UnityEngine.InputSystem.Key.F8,
            @"時間停止のトグルキー");

        SampleHotkey = new global::BunnyGarden2FixMod.Utils.HotkeyConfig(cfg,
            "Hotkey", "Sample",
            global::UnityEngine.InputSystem.Key.F12,
            global::BunnyGarden2FixMod.Utils.ControllerButton.Start,
            @"サンプルホットキー。
コントローラーの場合は ControllerModifier と同時押しが必要です。");

        SampleToggle = cfg.Bind("Sample", "SampleToggle",
            false,
            @"テスト用 Toggle");

        SampleSlider = cfg.Bind("Sample", "SampleSlider",
            0.5f,
            new ConfigDescription(
                @"テスト用 Slider",
                new AcceptableValueRange<float>(0.0f, 1.0f)));

    }

    // ─── UIEntries: F9 設定パネルが foreach で描画する ──
    public static System.Collections.Generic.IReadOnlyList<global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta> UIEntries { get; } = new global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta[]
    {
        new global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta
        {
            Category = "Sample",
            Order    = 10,
            Label    = "テスト Toggle",
            Desc     = "テスト用 Toggle",
            Kind     = global::BunnyGarden2FixMod.Patches.Settings.UIKind.Toggle,
            Accessor = new global::BunnyGarden2FixMod.Patches.Settings.BoolAccessor(() => SampleToggle),
        },
        new global::BunnyGarden2FixMod.Patches.Settings.UIEntryMeta
        {
            Category = "Sample",
            Order    = 20,
            Label    = "テスト Slider",
            Desc     = "テスト用 Slider",
            Kind       = global::BunnyGarden2FixMod.Patches.Settings.UIKind.Slider,
            SliderMin  = 0f,
            SliderMax  = 1f,
            SliderStep = 0.1f,
            Format     = "{0:F2}",
            Accessor = new global::BunnyGarden2FixMod.Patches.Settings.FloatAccessor(() => SampleSlider, 0.1f),
        },
    };

}
